# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pessoa.proto

require 'google/protobuf'


descriptor_data = "\n\x0cpessoa.proto\x12\x06pessoa\"5\n\x06Pessoa\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\r\n\x05idade\x18\x02 \x01(\x05\x12\x0e\n\x06\x61ltura\x18\x03 \x01(\x02\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pessoa
  Pessoa = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pessoa.Pessoa").msgclass
end
