# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mflix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmflix.proto\"r\n\x05\x46ilme\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x0f\n\x07\x64iretor\x18\x03 \x01(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x0e\n\x06\x61tores\x18\x05 \x03(\t\x12\x0e\n\x06genero\x18\x06 \x03(\t\x12\x0f\n\x07\x64uracao\x18\x07 \x01(\x02\"+\n\x06Pedido\x12\n\n\x02op\x18\x01 \x01(\x05\x12\x15\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x06.Filme\"7\n\x0b\x43onfirmacao\x12\x11\n\tresultado\x18\x01 \x01(\x05\x12\x15\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x06.Filmeb\x06proto3')



_FILME = DESCRIPTOR.message_types_by_name['Filme']
_PEDIDO = DESCRIPTOR.message_types_by_name['Pedido']
_CONFIRMACAO = DESCRIPTOR.message_types_by_name['Confirmacao']
Filme = _reflection.GeneratedProtocolMessageType('Filme', (_message.Message,), {
  'DESCRIPTOR' : _FILME,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:Filme)
  })
_sym_db.RegisterMessage(Filme)

Pedido = _reflection.GeneratedProtocolMessageType('Pedido', (_message.Message,), {
  'DESCRIPTOR' : _PEDIDO,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:Pedido)
  })
_sym_db.RegisterMessage(Pedido)

Confirmacao = _reflection.GeneratedProtocolMessageType('Confirmacao', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMACAO,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:Confirmacao)
  })
_sym_db.RegisterMessage(Confirmacao)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILME._serialized_start=15
  _FILME._serialized_end=129
  _PEDIDO._serialized_start=131
  _PEDIDO._serialized_end=174
  _CONFIRMACAO._serialized_start=176
  _CONFIRMACAO._serialized_end=231
# @@protoc_insertion_point(module_scope)
