# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mflix.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mflix.proto", :syntax => :proto3) do
    add_message "Filme" do
      optional :id, :int32, 1
      optional :titulo, :string, 2
      optional :diretor, :string, 3
      optional :ano, :int32, 4
      repeated :atores, :string, 5
      repeated :genero, :string, 6
      optional :duracao, :float, 7
    end
    add_message "Pedido" do
      optional :op, :int32, 1
      optional :filme, :message, 2, "Filme"
    end
    add_message "Confirmacao" do
      optional :resultado, :int32, 1
      optional :filme, :message, 2, "Filme"
    end
  end
end

Filme = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Filme").msgclass
Pedido = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Pedido").msgclass
Confirmacao = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Confirmacao").msgclass
