# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mflix.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmflix.proto\x12\x05mflix\"u\n\x05\x46ilme\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06titulo\x18\x02 \x01(\t\x12\x11\n\tdiretores\x18\x03 \x03(\t\x12\x0b\n\x03\x61no\x18\x04 \x01(\x05\x12\x0e\n\x06\x61tores\x18\x05 \x03(\t\x12\x0f\n\x07generos\x18\x06 \x03(\t\x12\x0f\n\x07\x64uracao\x18\x07 \x01(\x05\"&\n\x06\x46ilmes\x12\x1c\n\x06\x66ilmes\x18\x01 \x03(\x0b\x32\x0c.mflix.Filme\"?\n\x06Pedido\x12\n\n\x02op\x18\x01 \x01(\x05\x12\x1b\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x0c.mflix.Filme\x12\x0c\n\x04\x66unc\x18\x03 \x01(\x05\"K\n\x0b\x43onfirmacao\x12\x11\n\tresultado\x18\x01 \x01(\x05\x12\x1b\n\x05\x66ilme\x18\x02 \x01(\x0b\x32\x0c.mflix.Filme\x12\x0c\n\x04\x65rro\x18\x03 \x01(\x05\x62\x06proto3')



_FILME = DESCRIPTOR.message_types_by_name['Filme']
_FILMES = DESCRIPTOR.message_types_by_name['Filmes']
_PEDIDO = DESCRIPTOR.message_types_by_name['Pedido']
_CONFIRMACAO = DESCRIPTOR.message_types_by_name['Confirmacao']
Filme = _reflection.GeneratedProtocolMessageType('Filme', (_message.Message,), {
  'DESCRIPTOR' : _FILME,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:mflix.Filme)
  })
_sym_db.RegisterMessage(Filme)

Filmes = _reflection.GeneratedProtocolMessageType('Filmes', (_message.Message,), {
  'DESCRIPTOR' : _FILMES,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:mflix.Filmes)
  })
_sym_db.RegisterMessage(Filmes)

Pedido = _reflection.GeneratedProtocolMessageType('Pedido', (_message.Message,), {
  'DESCRIPTOR' : _PEDIDO,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:mflix.Pedido)
  })
_sym_db.RegisterMessage(Pedido)

Confirmacao = _reflection.GeneratedProtocolMessageType('Confirmacao', (_message.Message,), {
  'DESCRIPTOR' : _CONFIRMACAO,
  '__module__' : 'mflix_pb2'
  # @@protoc_insertion_point(class_scope:mflix.Confirmacao)
  })
_sym_db.RegisterMessage(Confirmacao)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILME._serialized_start=22
  _FILME._serialized_end=139
  _FILMES._serialized_start=141
  _FILMES._serialized_end=179
  _PEDIDO._serialized_start=181
  _PEDIDO._serialized_end=244
  _CONFIRMACAO._serialized_start=246
  _CONFIRMACAO._serialized_end=321
# @@protoc_insertion_point(module_scope)
